/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoegame;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class MainWindowForm extends javax.swing.JFrame {

    /**
     * Creates new form MainWindowForm
     */
    public MainWindowForm() {
       super("Tic Tac Toe");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        setSize(507, 525);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JLabel();
        singlePlayer = new javax.swing.JButton();
        multiPlayer = new javax.swing.JButton();
        subHeader = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        header.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setText("Tic Tac Toe");
        getContentPane().add(header);
        header.setBounds(190, 70, 150, 50);

        singlePlayer.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        singlePlayer.setText("Single Player");
        singlePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singlePlayerActionPerformed(evt);
            }
        });
        getContentPane().add(singlePlayer);
        singlePlayer.setBounds(60, 260, 130, 40);

        multiPlayer.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        multiPlayer.setText("Multiplayer");
        multiPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiPlayerActionPerformed(evt);
            }
        });
        getContentPane().add(multiPlayer);
        multiPlayer.setBounds(330, 260, 130, 40);

        subHeader.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        subHeader.setForeground(new java.awt.Color(255, 255, 255));
        subHeader.setText("Choose a mode to Continue");
        getContentPane().add(subHeader);
        subHeader.setBounds(10, 120, 500, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(505, 526));
        getContentPane().add(background);
        background.setBounds(0, 0, 505, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void singlePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singlePlayerActionPerformed
        // TODO add your handling code here:
        //TicTacToeAI t=new TicTacToeAI();
       // t.run();
        new SinglePlayer();
        setVisible(false);
    }//GEN-LAST:event_singlePlayerActionPerformed

    private void multiPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiPlayerActionPerformed
        setVisible(false);
        new ConnectMultiPlayer();
    }//GEN-LAST:event_multiPlayerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindowForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel header;
    private javax.swing.JButton multiPlayer;
    private javax.swing.JButton singlePlayer;
    private javax.swing.JLabel subHeader;
    // End of variables declaration//GEN-END:variables
}
